/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 进程存活检查
         * @description 规划契约；后端尚未实现。
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出公开演示任务
         * @description 规划契约；后端尚未实现。 仅访问脱敏观测，不暴露故障注入真值。
         */
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取脱敏告警与时间窗口
         * @description 规划契约；后端尚未实现。 仅访问脱敏观测，不暴露故障注入真值。
         */
        get: operations["getIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出六种诊断策略
         * @description 规划契约；后端尚未实现。
         */
        get: operations["listStrategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 运行列表
         * @description 规划契约；后端尚未实现。
         */
        get: operations["listRuns"];
        put?: never;
        /**
         * 创建受预算约束的诊断运行
         * @description 规划契约；后端尚未实现。
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 状态与竞争假设快照
         * @description 规划契约；后端尚未实现。
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 请求取消运行
         * @description 规划契约；后端尚未实现。
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 增量读取事件
         * @description 规划契约；后端尚未实现。
         */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 增量读取证据
         * @description 规划契约；后端尚未实现。
         */
        get: operations["listEvidences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取完成运行的诊断报告
         * @description 规划契约；后端尚未实现。
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取项目预算账本
         * @description 规划契约；后端尚未实现。
         */
        get: operations["getBudget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            request_id: string;
            retryable: boolean;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        Incident: {
            incident_id: string;
            title: string;
            alert: string;
            service: string;
            /** Format: date-time */
            window_start: string;
            /** Format: date-time */
            window_end: string;
            dataset_version: string;
        };
        Strategy: {
            /** @enum {string} */
            strategy_id: "fixed" | "react" | "graph_greedy" | "competitive_cost" | "no_cost" | "random_probe";
            name: string;
            description: string;
        };
        Limits: {
            max_steps: number;
            max_llm_calls: number;
            max_wall_seconds: number;
            max_cost_micro_cny: number;
        };
        CreateRun: {
            incident_id: string;
            /** @enum {string} */
            strategy_id: "fixed" | "react" | "graph_greedy" | "competitive_cost" | "no_cost" | "random_probe";
            limits: components["schemas"]["Limits"];
        };
        Usage: {
            llm_calls: number;
            probe_count: number;
            input_tokens: number;
            output_tokens: number;
            settled_micro_cny: number;
            reserved_micro_cny: number;
            uncertain_micro_cny: number;
            probe_cost_units: number;
        };
        Hypothesis: {
            hypothesis_id: string;
            component: string;
            fault_type: string;
            /** @enum {string} */
            status: "active" | "supported" | "contradicted" | "unresolved";
            score: number;
            evidence_ids: string[];
            predictions: {
                tool_name: string;
                observation: string;
                /** @enum {string} */
                expected: "high" | "normal" | "low" | "unknown";
            }[];
        };
        Run: {
            run_id: string;
            incident_id: string;
            strategy_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "cancel_requested" | "completed" | "cancelled" | "failed";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
            trace_id: string;
            limits: components["schemas"]["Limits"];
            usage: components["schemas"]["Usage"];
            hypotheses: components["schemas"]["Hypothesis"][];
            last_event_seq: number;
            /** @enum {string} */
            stop_reason: "none" | "evidence_sufficient" | "ambiguous" | "step_limit" | "cost_limit" | "deadline" | "cancelled" | "dependency_error" | "worker_lost";
            model: string;
            config_hash: string;
            dataset_version: string;
        };
        CancelRun: {
            reason: string;
        };
        Event: {
            seq: number;
            /** Format: date-time */
            timestamp: string;
            /** @enum {string} */
            kind: "run_created" | "run_started" | "hypotheses_updated" | "probe_started" | "probe_finished" | "llm_finished" | "cancel_requested" | "run_finished" | "warning";
            message: string;
            evidence_ids: string[];
            hypothesis_ids: string[];
            span_id: string;
            decision?: {
                probe_id: string;
                disagreement_pairs: number;
                estimated_cost_units: number;
                utility: number;
                reason: string;
            };
        };
        Evidence: {
            evidence_id: string;
            probe_id: string;
            /** @enum {string} */
            tool_name: "query_metrics" | "query_logs" | "get_trace" | "read_config";
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            window_start: string;
            /** Format: date-time */
            window_end: string;
            summary: string;
            content_hash: string;
            /** @enum {string} */
            outcome: "ok" | "empty" | "timeout" | "error" | "truncated";
            source: string;
            span_id: string;
            seq: number;
        };
        Report: {
            run_id: string;
            /** @enum {string} */
            conclusion: "located" | "unresolved";
            component: string;
            fault_type: string;
            summary: string;
            evidence_ids: string[];
            alternatives: string[];
            limitations: string[];
            stop_reason: string;
            usage: components["schemas"]["Usage"];
        };
        Budget: {
            /** @enum {string} */
            currency: "CNY";
            cap_micro_cny: number;
            admission_cap_micro_cny: number;
            settled_micro_cny: number;
            reserved_micro_cny: number;
            uncertain_micro_cny: number;
            available_micro_cny: number;
        };
        IncidentList: {
            items: components["schemas"]["Incident"][];
        };
        StrategyList: {
            items: components["schemas"]["Strategy"][];
        };
        RunPage: {
            items: components["schemas"]["Run"][];
            /** @description 空字符串表示没有下一页 */
            next_cursor: string;
        };
        EventPage: {
            items: components["schemas"]["Event"][];
            /** @description 下一次 after_seq；没有新记录时等于本次 after_seq */
            next_cursor: number;
            has_more: boolean;
        };
        EvidencePage: {
            items: components["schemas"]["Evidence"][];
            /** @description 下一次 after_seq；使用内部证据递增序号，非数组下标 */
            next_cursor: number;
            has_more: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listIncidents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentList"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Incident"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求校验失败 */
            422: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listStrategies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyList"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description 请求校验失败 */
            422: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "incident_id": "demo_001",
                 *       "strategy_id": "competitive_cost",
                 *       "limits": {
                 *         "max_steps": 12,
                 *         "max_llm_calls": 16,
                 *         "max_wall_seconds": 180,
                 *         "max_cost_micro_cny": 250000
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["CreateRun"];
            };
        };
        responses: {
            /** @description 成功 */
            202: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 状态冲突或幂等键正文不同 */
            409: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求校验失败 */
            422: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 准入预算或并发额度不足 */
            429: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 必要依赖未就绪 */
            503: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求校验失败 */
            422: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "reason": "用户取消演示"
                 *     }
                 */
                "application/json": components["schemas"]["CancelRun"];
            };
        };
        responses: {
            /** @description 成功 */
            202: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求校验失败 */
            422: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求校验失败 */
            422: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEvidences: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求校验失败 */
            422: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description 资源不存在 */
            404: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 状态冲突或幂等键正文不同 */
            409: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 请求校验失败 */
            422: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBudget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
            /** @description 未预期内部错误；不回显堆栈 */
            500: {
                headers: {
                    /** @description 请求关联标识 */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
